---
- hosts: webservers
  become: true
  tasks:
  - name: Add Docker Ubuntu's repository key to APT's trusted package sources
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Update repositories cache and install "docker-ce" package
    apt:
      name: docker-ce
      update_cache: yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: ['python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Add user to docker group
    user:
      name: "{{ ansible_user }}"
      append: yes
      groups:
        - docker
